name: autobuild
run-name: "${{ format('{0} ({1})', github.workflow, 'gcc') }}"

on: 
   schedule:
     - cron:  '0 8 * * *'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mpv build workflow
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const repo="${{github.repository}}".split('/')[1];
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{github.repository_owner}}',
              repo,
              ref: '${{github.ref}}',
              workflow_id: 'mpv.yml',
              inputs: {
              winbuild_repo: "dyphire/mpv-winbuild-cmake",
              winbuild_ref: "patch",
              build_target: "all-64bit",
              compiler: "gcc",
              needclean: false,
              no_save_cache: false,
              release: true
              }
            })