name: MPV_OLDWAY

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * Sun'

jobs:
  build:
    name: Build MPV_OLDWAY
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Build
        shell: bash
        run: |
          sudo bash build_oldway.sh
      - uses: actions/upload-artifact@master
        with: 
          name: mpv-win
          #path: ~/**/mpv-x86_64*/
          path: /home/runner/work/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/mpv-x86_64*/
      - uses: actions/upload-artifact@master
        with:
          name: libmpv-win
          #path: ~/**/mpv-dev*/
          path: /home/runner/work/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/mpv-dev*/
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/*.7z
          tag: mpv_oldway
          overwrite: true
          file_glob: true
