name: MPV_OWN

on: 
  schedule:
    - cron: '0 8 * * */4'
  workflow_dispatch:
    inputs:
      clean:
        description: 'input anything if you want to clean build files'
        required: false
      cache_id:
        description: 'input cache_id if you want to renew cache'
        required: false
      release:
        description: "input 'false' if you don't want to release"
        required: false
        default: "true"

jobs:
  build_mpv:
    name: Build MPV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bit: [64]
    outputs:
      sha: ${{ steps.get_sha.outputs.sha }}

    steps:
      - uses: actions/checkout@v2
      - name: 'Get mpv latest commit sha'
        id: get_sha
        uses: actions/github-script@v5
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'mpv-player',
              repo: 'mpv',
              ref: `master`
            })
            core.setOutput('sha', String(commit.data.sha))
      - name: Get current time
        run: |
          echo "short_time=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
          echo "month=$(date "+%Y-%m")" >> $GITHUB_ENV
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: mpv-winbuild-cmake/build${{ matrix.bit }}
          key: ${{ runner.os }}-mpv-build${{ matrix.bit }}-${{ env.short_time }}-${{ steps.get_sha.outputs.sha }}-${{ github.event.inputs.cache_id }}
          restore-keys: |
            ${{ runner.os }}-mpv-build${{ matrix.bit }}-${{ env.short_time }}-${{ steps.get_sha.outputs.sha }}
            ${{ runner.os }}-mpv-build${{ matrix.bit }}-${{ env.short_time }}
            ${{ runner.os }}-mpv-build${{ matrix.bit }}-${{ env.month }}
      - name: Build
        id: build
        shell: bash
        run: |
          sudo bash build_own.sh "${{ matrix.bit }}" "${{ github.event.inputs.clean }}"
      - name: Collect error logs
        if: ${{ always() && steps.build.outcome == 'failure' }}
        run: |
          sudo 7z a logs.7z mpv-winbuild-cmake/build${{ matrix.bit }}/*-err.log -r
      - name: upload error logs
        uses: actions/upload-artifact@master
        if: ${{ always() && steps.build.outcome == 'failure' }}
        with:
          name: logs
          path: logs.7z

      - name: Upload artifact
        id: upload
        uses: kittaakos/upload-artifact-as-is@master
        with:
          path: mpv-winbuild-cmake/release/*.7z

  publish_release:
    name: Publish release
    needs: build_mpv
    if: ${{ github.event.inputs.release != 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
    
      - name: Get current time
        run: |
          echo "long_time=$(date "+%Y-%m-%d %H:%M")" >> $GITHUB_ENV
          echo "short_time=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
      - name: Commit version & remove existing tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git fetch --tags
          git checkout version || git checkout -b version origin/version || ( git checkout --orphan version && git rm -rf . )
          echo -e "${{ env.short_time }}" > version
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version
          git diff-index --quiet HEAD || ( git commit -m "${{ env.short_time }}" && git push origin version )
          if [ $(git tag -l "${{ env.short_time }}") ] ;then
            gh release delete "${{ env.short_time }}" || true
            git push --delete origin "${{ env.short_time }}" || true
            git tag -d "${{ env.short_time }}" || true
          fi
          git checkout main
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*/*.7z"
          commit: version
          name: "MPV_OWN ${{ env.long_time }}"
          body: "**MPV git commit**: https://github.com/mpv-player/mpv/commit/${{ needs.build_mpv.outputs.sha }}\n**Test**: Build with libass from [dyphire/libass_dev](https://github.com/dyphire/libass/tree/dev), it may fix some problems for scaled with PlayResX, font: use iconv to handle non-unicode cmap microsoft fonts\n**Remember**: This is not perfect\n**Build Time**: ${{ env.long_time }}"
          tag: "mpv_own-${{ env.short_time }}"
          allowUpdates: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prune old releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git checkout main
          bash prunetags.sh
